services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3000
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "3001:3000"
    command: npm run dev
