version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      RAILS_ENV: development
      DB_HOST: db
    depends_on:
      - db

  db:
    image: postgres:16
    env_file:
      - .env
    environment:
      POSTGRES_DB: streaming_service
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
