FROM ruby:3.3
RUN apt-get update -qq && apt-get install -y --no-install-recommends nodejs postgresql-client ffmpeg imagemagick
WORKDIR /app
COPY Gemfile Gemfile.lock ./
RUN bundle install
COPY . .
CMD ["rails", "s", "-b", "0.0.0.0"]
